<?php

//use Shopware_Controllers_Frontend_RoutingDemo;

class Shopware_Controllers_Frontend_RoutingDemo extends Enlight_Controller_Action
{
    public function preDispatch()
    {
        $this->view->addTemplateDir(__DIR__.'/../../Resources/views');
        //parent::preDispatch(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {

    }

}
