<?php

class Shopware_Controllers_Frontend_Technology extends Enlight_Controller_Action
{
    public function preDispatch()
    {
        $this->view->addTemplateDir(__DIR__.'/../../Resources/views');
        parent::preDispatch(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $connection = $this->get('dbal_connection');
        $builder = $connection->createQueryBuilder();
        $query = $builder->select('svt.name, svt.description')
            ->from('s_virtua_technology','svt')
            ->leftJoin('svt','s_media','sm','svt.logo = sm.id');

        $technologies = $query->execute()->fetchAll();
        $this->View()->assign('techList',$technologies);

    }
    public function detailAction()
    {
        $wordId = $this->Request()->getParam('nameId');

        /** @var \Doctrine\DBAL\Query\QueryBuilder $queryBuilder */
        $queryBuilder = $this->container->get('dbal_connection')->createQueryBuilder();

        $wordData = $queryBuilder->select('name, description')
            ->from('s_virtua_technology', 'svt')
            ->where('id = :id')
            ->setParameter(':id', $wordId)
            ->execute()
            ->fetch();

        $this->View()->assign($wordData);
    }
}
